### ISSUE TITLE
Add  Snake-water-gun-game file in python with proper code

### ISSUE THREAD

**Issue by Arpitgupta1014** [Arpitgupta1014/Snake-water-gun-game#1]
Make sure this before making PR regarding it :

-> Appropriate title for PR
-> Making another branch with an appropriate name.
-> Comment on the file at the top with the link to the question
Happy Coding 👍

**Comment by singhAman05** [comment]
sir can i work on this problem

**Comment by flow6979** [comment]
hey @Arpitgupta1014 can you please assign this to me. i am very much excited to contribute to this repository.
